import React, { useEffect, useState } from "react";
import axios from "axios";
import Layout from "../components/Layout/Layout";
import "./ReferralIncome.css";
import {  FaSearch,  FaUsers,  FaMoneyBillWave, FaLayerGroup} from "react-icons/fa";

function ReferralIncome() {

  const [incomeHistory, setIncomeHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  useEffect(() => {
    fetchIncomeHistory();
  }, []);

  const fetchIncomeHistory = async () => {

    try {

      const token = localStorage.getItem("token");

      const res = await axios.get(
        "http://localhost:5000/api/referral-income/history",
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      setIncomeHistory(res.data.incomeHistory);

    } catch (error) {

      console.log(error);

    } finally {

      setLoading(false);

    }

  };

  const filteredIncome = incomeHistory.filter((item) =>
    item.generatedByUser?.fullName
      ?.toLowerCase()
      .includes(search.toLowerCase())
  );

  const totalIncome = incomeHistory.reduce(
    (sum, item) => sum + item.incomeAmount,
    0
  );

  return (
    <Layout>

      <div className="income-page">

        <div className="income-header">

  <div>
    <h1>Referral Income</h1>
    <p>
      Track your team earnings and level income
    </p>
  </div>

  <div className="search-box">

    <FaSearch className="search-icon" />

    <input
      type="text"
      placeholder="Search member..."
      value={search}
      onChange={(e) =>
        setSearch(e.target.value)
      }
    />

  </div>

</div>

       <div className="income-summary-grid">

  <div className="summary-card income">

    <div className="summary-icon">
      <FaMoneyBillWave />
    </div>

    <div>
      <h4>Total Income</h4>
      <h2>
        ₹ {totalIncome.toLocaleString()}
      </h2>
    </div>

  </div>

  <div className="summary-card members">

    <div className="summary-icon">
      <FaUsers />
    </div>

    <div>
      <h4>Total Records</h4>
      <h2>{incomeHistory.length}</h2>
    </div>

  </div>

  <div className="summary-card levels">

    <div className="summary-icon">
      <FaLayerGroup />
    </div>

    <div>
      <h4>Levels Active</h4>
      <h2>
        {
          [...new Set(
            incomeHistory.map(
              (item) => item.level
            )
          )].length
        }
      </h2>
    </div>

  </div>

</div>

        {loading ? (

          <h3>Loading...</h3>

        ) : filteredIncome.length === 0 ? (

          <div className="empty-state">
            No Referral Income Found
          </div>

        ) : (

          <table className="income-table">

            <thead>

              <tr>
                <th>Generated By</th>
                <th>Email</th>
                <th>Level</th>
                <th>Income</th>
                <th>Date</th>
              </tr>

            </thead>

            <tbody>

              {filteredIncome.map((item) => (

                <tr key={item._id}>

                  <td>
                    {item.generatedByUser?.fullName}
                  </td>

                  <td>
                    {item.generatedByUser?.email}
                  </td>

                  <td>
  <span
    className={`level-badge level-${item.level}`}
  >
    Level {item.level}
  </span>
</td>

                <td className="income-amount">
  ₹ {item.incomeAmount.toLocaleString()}
</td>

                  <td>
                    {new Date(
                      item.incomeDate
                    ).toLocaleDateString("en-IN")}
                  </td>

                </tr>

              ))}

            </tbody>

          </table>

        )}

      </div>

    </Layout>
  );
}

export default ReferralIncome;